services:
  - type: web
    name: fb-comment-absorber
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
