services:
  - type: web
    name: comment-absorber
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_web.py
    envVars:
      - key: PORT
        value: 5000
